stages:
  - build

variables:
  VERSION: 1.0.0

build:
  stage: build
  image: alpine:latest
  only:
    - pipelines
  before_script:
    - apk add zip curl jq
  script:
    - echo $INJECTOR_RELEASE_TAG
    - echo $INJECTOR_ARCHIVE_NAME
  variables:
    GITHUB_API_URL: https://api.github.com
